language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - APP_ENV=development CC_TEST_REPORTER_ID=efd18a36922628f0536f2f08cf7ceca763f5f2feb6f3638037381487ca3312ae

matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.4
      env: dependencies=lowest
  allow_failures:
    - php: 7.1
    - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable --no-interaction; fi;
    - touch .env
    - echo 'date.timezone = Europe/Berlin' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - php vendor/bin/php-coveralls -v
    - vendor/bin/test-reporter
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
